// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkMLgxm0iF6OG7eC9sho6pc-MlXnlr9e4',
    appId: '1:624468983805:web:6c32b0fe668c799fdae394',
    messagingSenderId: '624468983805',
    projectId: 'cins467-4b5c8',
    authDomain: 'cins467-4b5c8.firebaseapp.com',
    storageBucket: 'cins467-4b5c8.appspot.com',
    measurementId: 'G-WY9SLB9S70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALl3ViU61qk_uw1WpU5-gtqU-fpXqnjBk',
    appId: '1:624468983805:android:a6bd78cbae5c8af3dae394',
    messagingSenderId: '624468983805',
    projectId: 'cins467-4b5c8',
    storageBucket: 'cins467-4b5c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzwCg80hkRuB1r-yelAZ-l_6Lk3TinnIo',
    appId: '1:624468983805:ios:6499f13684f930c0dae394',
    messagingSenderId: '624468983805',
    projectId: 'cins467-4b5c8',
    storageBucket: 'cins467-4b5c8.appspot.com',
    androidClientId: '624468983805-g5nniq2ubiigiftc0i6mfpaqsfphe5d3.apps.googleusercontent.com',
    iosClientId: '624468983805-79d8totf8lphcjtc445kpd0fb7l7anvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzwCg80hkRuB1r-yelAZ-l_6Lk3TinnIo',
    appId: '1:624468983805:ios:0185f3bca0f55680dae394',
    messagingSenderId: '624468983805',
    projectId: 'cins467-4b5c8',
    storageBucket: 'cins467-4b5c8.appspot.com',
    androidClientId: '624468983805-g5nniq2ubiigiftc0i6mfpaqsfphe5d3.apps.googleusercontent.com',
    iosClientId: '624468983805-nuki5damkf9hodhnvebm6i0ai50qkbq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject.RunnerTests',
  );
}
